//Daniel Marcos Guerra Gómez
import java.util.Scanner; //Importación de paquetes
public class U2_R2_Ej5_Daniel{
	public static void main(String []args){
	//Declarar variables
	int numero;
	Scanner teclado=new Scanner(System.in);
	//Desarrollo del programa
	System.out.println("Introduzca un número entero entre 0 y 9999");
	numero=teclado.nextInt();
	if(numero>=0 && numero<=9999){
		switch(numero){
		case 0: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 11: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 22: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 33: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 44: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 55: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 66: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 77: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 88: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 99: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 101: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 111: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 121: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 131: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 141: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 151: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 161: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 171: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 181: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 191: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 202: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 212: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 222: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 232: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 242: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 252: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 262: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 272: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 282: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 292: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 303: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 313: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 323: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 333: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 343: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 353: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 363: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 373: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 383: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 393: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 404: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 414: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 424: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 434: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 444: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 454: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 464: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 474: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 484: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 494: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 505: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 515: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 525: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 535: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 545: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 555: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 565: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 575: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 585: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 595: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 606: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 616: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 626: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 636: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 646: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 656: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 666: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 676: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 686: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 696: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 707: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 717: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 727: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 737: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 747: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 757: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 767: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 777: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 787: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 797: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 808: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 818: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 828: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 838: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 848: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 858: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 868: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 878: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 888: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 898: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 909: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 919: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 929: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 939: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 949: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 959: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 969: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 979: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 989: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 999: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1001: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1111: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1221: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1331: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1441: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1551: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1661: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1771: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1881: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 1991: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2002: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2112: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2222: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2332: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2442: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2552: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2662: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2772: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2882: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 2992: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3003: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3113: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3223: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3333: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3443: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3553: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3663: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3773: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3883: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 3993: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4004: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4114: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4224: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4334: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4444: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4554: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4664: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4774: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4884: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 4994: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5005: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5115: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5225: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5335: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5445: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5555: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5665: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5775: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5885: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 5995: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6006: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6116: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6226: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6336: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6446: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6556: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6666: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6776: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6886: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 6996: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7007: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7117: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7227: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7337: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7447: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7557: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7667: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7777: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7887: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 7997: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8008: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8118: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8228: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8338: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8448: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8558: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8668: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8778: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8888: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 8998: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9009: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9119: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9229: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9339: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9449: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9559: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9669: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9779: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9889: System.out.println("El número "+numero+" es capicúa.");
        break;
		case 9999: System.out.println("El número "+numero+" es capicúa.");
        break;
		//Indicar que el número es capicua
		default: System.out.println("El número "+numero+" no es capicúa.");//Indicar que el número no es capicua
		}
	}
	else{
		System.out.println("El número "+numero+" no esta entre el 0 y el 9999.");//Mostrar error por no estar entre 0 y 9999
	}
	//Mostrar resultado
	}//Fin main
}//Fin clase
